name: Rust Compile and Release


on: 
  workflow_call:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Edit Cargo.toml
        run: |
          sed -i 's/^openssl.*/openssl = {version = "0.10", features = ["vendored"]}/g' Cargo.toml
          echo 'opt-level = 3' >> Cargo.toml
          echo 'debug = false' >> Cargo.toml
          echo 'debug-assertions = false' >> Cargo.toml
          echo 'overflow-checks = false' >> Cargo.toml
          echo 'lto = "fat"' >> Cargo.toml
          echo 'strip = "debuginfo"' >> Cargo.toml
          echo 'panic = "unwind"' >> Cargo.toml
          echo 'incremental = false' >> Cargo.toml
          echo 'codegen-units = 2' >> Cargo.toml
          echo 'rpath = false' >> Cargo.toml

      - name: Install musl-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Compile Binary
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: '-C target-feature=+crt-static -C link-self-contained=yes'
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl --target-dir target

      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ github.event.repository.name }}
          generate_release_notes: true
